repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        exclude: ^frontend/(node_modules|\.next)/
      - id: ruff-format
        exclude: ^frontend/(node_modules|\.next)/
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: ^frontend/(node_modules|\.next)/
